apiVersion: apps/v1
kind: Deployment
metadata:
  name: badapp
spec:
  selector:
    matchLabels:
      app: badapp
  template:
    metadata:
      labels:
        app: badapp
    spec:
      containers:
      - image: litmuschaos/memleak:latest
        name: badapp
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 100Mi