apiVersion: apps/v1
kind: Deployment
metadata:
  name: badapp
spec:
  selector:
    matchLabels:
      app: badapp
  template:
    metadata:
      labels:
        app: badapp
    containers:
    - image: otterley/memleak
      name: badapp
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"