apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: web-services
spec:
  ports:
  - port: 81
    targetPort: 81
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    app.komodor.com/app: https://github.com/bwilliam79/Komodor-App
    app.komodor.com/app.ref: 4aa821d
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 81
        volumeMounts:
        - name: nginx-index-file
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-index-file
        configMap:
          name: index-html-configmap