kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: web-services
spec:
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-index-file
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: nginx-index-file
    configMap:
      name: index-html-configmap
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: web-services
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: web-services
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /nginx(/|$)(.*)
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---