apiVersion: apps/v1
kind: Deployment
metadata:
  name: badapp
spec:
  selector:
    matchLabels:
      app: badapp
  template:
    metadata:
      labels:
        app: badapp
    spec:
      containers:
      - image: polinux/stress
        name: badapp
      resources:
        requests:
          memory: "50M"
        limits:
          memory: "100M"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "25M", "--vm-hang", "1"]