apiVersion: v1
kind: Pod
metadata:
  name: badapp
spec:
  selector:
    matchLabels:
      app: badapp
  template:
    metadata:
      labels:
        app: badapp
  containers:
  - image: polinux/stress
    name: badapp
  resources:
    requests:
      memory: "100Mi"
    limits:
      memory: "200Mi"
  command: ["stress"]
  args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]